import logo from 'sp-placeholder'

/* You can update the data in this file
 * If you use `{ desks: ['Desk-1', 'Desk-2'], articles: [{ title: 'Article-1' }, { title: 'Article-2' }] }`
 * You will get `Desk-1 => [Article-1, Article-2]` and `Desk-2 => ['Article-1', 'Article-2']`
 * If the desks or articles is not enough, it will rewind to the start of the array automatically
 * And if you want difference article for difference desk, you can use:
 * `{ desks: ['Desk-1', 'Desk-2'], articles: { 'Desk-1': [...], 'Desk-2': [...] } }`
 */
export default {
  desks: [
    'Positive',
    'Order',
    'Love',
    'Spiritual',
    'Body',
    'Science',
    'Art',
    'Meditation',
    'Mystery',
    'History',
    'Legacy',
    'Radience',
    'Sweet',
    'Thrust',
  ],
  pages: ['About Us', 'Contact Us', 'Submit a proposal', 'Using our stories'],
  logo,
  site: {
    name: 'Hero Undark',
    facebook: 'https://www.example.com',
    twitter: 'https://www.example.com',
    instagram: 'https://www.example.com',
    linkedin: 'https://www.example.com',
    youtube: 'https://www.example.com',
    pinterest: 'https://www.example.com',
    whatsapp: 'https://www.example.com',
    reddit: 'https://www.example.com',
    tiktok: 'https://www.example.com',
    geneva: 'https://www.example.com',
  },
  articles: {
    Positive: [
      {
        title: 'Man Found Having Tea Party With Rabbit.',
        blurb:
          'Consectetur esse pariatur incididunt nulla et reprehenderit culpa sit nisi laborum dolor eiusmod incididunt excepteur. Est laborum aute excepteur nostrud. Et consequat voluptate cupidatat enim dolore ea quis deserunt consequat officia Lorem incididunt. Consectetur fugiat sunt nisi id aute ullamco.',
        headline: 'https://picsum.photos/800/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Sanjay Rhodes', url: 'https://example.com' }],
      },
    ],
    Order: [
      {
        title: 'Peculiar Guillotine Likely To Win',
        blurb: 'My name is Sharlay Stelljes no matter what my step-mum tells you. ',
        headline: 'https://picsum.photos/900/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Amalie Snider', url: 'https://example.com' }],
      },
      {
        title: 'Local Man Wins Carrot Growing Contest For the Third Time',
        blurb: 'The world is full of people who are in love with Mav Asmerom.',
        headline: 'https://picsum.photos/800/700',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Martina Rosales', url: 'https://example.com' }],
      },
    ],
    Love: [
      {
        title: 'Viral Photo of Rabbit Had Been Photoshopped',
        blurb: "If I'd become a painter, there'd be a few less vampires on the planet.",
        headline: 'https://picsum.photos/600/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
      {
        title: 'Local man Set to Fly Out and Help With Tsunami Relief Effort',
        blurb: 'Jeannie was known for speaking out about healthcare. ',
        headline: 'https://picsum.photos/600/700',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Ian Atkinson', url: 'https://example.com' }],
      },
    ],
    Spiritual: [
      {
        title: 'Mock Data',
        blurb: 'This mock data helps see scroll menu in Desktop View, removed in production block',
        headline: 'https://picsum.photos/600/1000',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
      {
        title: 'Mock Data',
        blurb: 'This mock data helps see scroll menu in Desktop View',
        headline: 'https://picsum.photos/id/1/800/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
      {
        title: 'Mock Data',
        blurb: 'This mock data helps see scroll menu in Desktop View',
        headline: 'https://picsum.photos/id/1/800/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
      {
        title: 'Mock Data',
        blurb: 'This mock data helps see scroll menu in Desktop View',
        headline: 'https://picsum.photos/id/1/800/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
      {
        title: 'Mock Data',
        blurb: 'This mock data helps see scroll menu in Desktop View',
        headline: 'https://picsum.photos/id/1/800/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
      {
        title: 'Mock Data',
        blurb: 'This mock data helps see scroll menu in Desktop View',
        headline: 'https://picsum.photos/id/1/800/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
      {
        title: 'Mock Data',
        blurb: 'This mock data helps see scroll menu in Desktop View',
        headline: 'https://picsum.photos/id/1/800/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
      {
        title: 'Mock Data',
        blurb: 'This mock data helps see scroll menu in Desktop View',
        headline: 'https://picsum.photos/id/1/800/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
      {
        title: 'Mock Data',
        blurb: 'This mock data helps see scroll menu in Desktop View',
        headline: 'https://picsum.photos/id/1/800/600',
        headlineCaption: 'This is caption',
        url: 'https://example.com',
        time: new Date(),
        authors: [{ name: 'Persephone Whittaker', url: 'https://example.com' }],
      },
    ],
  },
  article: {
    title: 'Man Buys Jackets For Low Income Local Family',
    blurb: 'Sampson Crane is my muse.',
    headline: 'https://i.picsum.photos/id/111/800/600.jpg?hmac=eBUjTsKH_Ag9GUgKs0t1NwGjziFJRRlmYYrmTqyt3L8',
    headlineCaption: 'This is caption',
    url: 'https://example.com',
    desk: 'Editorial Mission',
    time: new Date(),
    authors: [{ name: 'Bryn Iles', url: 'https://example.com' }],
  },
}
